common_args:
  training_type: "simulation"
  random_seed: 0
  config_version: "release"
  # vorher war dev, mqtt funktioniert nicht
  # oben rechts profile -> copy account key -> create new project
  mlops_api_key: 8a24eda02ab84510878929f287b1b8df
  mlops_project_name: absolutertest
  mlops_run_name: fedml_torch_fedavg_mnist_lr_1

data_args:
  dataset: "mnist"
  data_cache_dir: ~/fedml_data
  partition_method: "hetero"
  partition_alpha: 0.5

model_args:
  model: "cnn" 
  # model: "lr" # for faster testing
  # no such model definition, please check the argument spelling or customize your own model

train_args:
  federated_optimizer: "FedAvg"
  client_id_list: "[]"
  client_num_in_total: 1000
  client_num_per_round: 10
  comm_round: 200
  epochs: 1
  batch_size: 10
  client_optimizer: sgd
  learning_rate: 0.03
  weight_decay: 0.001

validation_args:
  frequency_of_the_test: 5

device_args:
  using_gpu: false
  # using_gpu: true
  gpu_id: 0

comm_args:
  backend: "sp"

tracking_args:
  enable_tracking: true
   # When running on MLOps platform(open.fedml.ai), the default log path is at ~/fedml-client/fedml/logs/ and ~/fedml-server/fedml/logs/
  enable_wandb: true
  wandb_key: a2d90cdeb8de7e5e4f8baf1702119bcfee78d1ee
  wandb_entity: lifelikemaik
  wandb_project: fedml-sp
  run_name: fedml_torch_fedavg_mnist_lr
  using_mlops: false