common_args:
  training_type: "simulation"
  random_seed: 0
  config_version: "release"
  # mlops_api_key: 8a24eda02ab84510878929f287b1b8df
  # mlops_project_name: absolutertest
  # mlops_run_name: fedml_mpi_decentralized_fl_example

data_args:
  # dataset: "mnist"
  dataset: "femnist" # nothing changed
  data_cache_dir: ~/fedml_data
  partition_method: "hetero"
  partition_alpha: 0.5

model_args:
  # model: "lr" # for faster testing
  model: "cnn" 

train_args:
  federated_optimizer: "decentralized_fl" # simple message exchange between clients
  client_id_list: "[]"
  client_num_in_total: 1000
  client_num_per_round: 4
  comm_round: 50
  epochs: 1
  batch_size: 10
  client_optimizer: sgd
  learning_rate: 0.03
  weight_decay: 0.001

validation_args:
  frequency_of_the_test: 5

device_args:
  worker_num: 4 # was macht diese zahl genau?
  using_gpu: false

comm_args:
  backend: "MPI"
  is_mobile: 0


tracking_args:
   # When running on MLOps platform(open.fedml.ai), the default log path is at ~/fedml-client/fedml/logs/ and ~/fedml-server/fedml/logs/
  enable_wandb: false
  wandb_key: a2d90cdeb8de7e5e4f8baf1702119bcfee78d1ee
  wandb_project: fedml
  wandb_name: fedml_torch_fedavg_mnist_lr
  # enable_tracking: true # for fedml website
